Il faut trouver un moyen de désérialiser des listes de Body (hétérogènes)
com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of ch.elmootan.core.physics.Body, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information